version: "3"

services:
  application:
    build: ./app
    restart: "always"
    depends_on:
      - db
    ports:
      - '8080:80'
  db:
    image: mysql
    restart: always
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "lm359xDB"
